### ISSUE TITLE
photo dataset

### ISSUE THREAD

**Issue by stone100010** [kwea123/nerf_pl#10]
Thank you for writing nerf_ PL, I'd like to ask you what are the specific requirements for photographing dataset.

**Comment by kwea123** [comment]
I don't understand your question. You can write in Chinese, it helps me to understand more.

**Comment by stone100010** [comment]
感谢！我想了解一下拍摄的照片有什么具体的要求，我拍了一些玩偶的图片，https://github.com/Fyusion/LLFF/blob/master/demo.sh运行时，相关文件创建不出来，并报如下的错误：
[rawvideo demuxer @ 0x55de00b6a7a0] Unable to parse option value "0x0" as image size
[rawvideo demuxer @ 0x55de00b6a7a0] Error setting option video_size to value 0x0.
pipe:: Invalid argument
按照官方的图片并没有出现报错，我的图片很明显有问题，但是我暂时还没找到，抱歉打扰您了，再次感谢您！

**Comment by kwea123** [comment]
我沒用過LLFF，不過你先看是在哪一步出錯的吧。他那有4步，如果是最後render才出錯我覺得就是你安裝的問題，跟圖片沒關係。如果是前面就出錯那可能是圖片，或是colmap

**Comment by stone100010** [comment]
好的
