### ISSUE TITLE
Error running `python img2poses.py $your-images-folder`

### ISSUE THREAD

**Issue by asbeg** [kwea123/nerf_pl#104]
Hello,
I have followed your example to train NERF on my own data. So I have seen you and other guys have some success with single object scene?
I am trying to run `python img2poses.py $your-images-folder` and get this ERROR.
Can you explain what the problem might be and how to fix it ?
Im using MacOS based M1.

```Need to run COLMAP [option_manager.cc:811] Check failed: ExistsDir(*image_path) ERROR: Invalid options provided. Traceback (most recent call last): File "imgs2poses.py", line 18, in <module> gen_poses(args.scenedir, args.match_type) File "/Users/ab/ProjectTest/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses run_colmap(basedir, match_type) File "/Users/ab/ProjectTest/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) ) File "/opt/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "/opt/anaconda3/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/Users/ab/ProjectTest/imgs_nerf/database.db', '--image_path', '/Users/ab/ProjectTest/imgs_nerf/images', '--ImageReader.single_camera', '1']' returned non-zero exit status 1.```

**Comment by Holmes-Alan** [comment]
how do you resolve the problem?
