### ISSUE TITLE
torchsearchsorted missing

### ISSUE THREAD

**Issue by Riretta** [kwea123/nerf_pl#107]
**Describe the bug**
in rendering.py, there is import torchsearchsorted but it is missing and I do not get where is this file or library

**To Reproduce**
I run the train.py with commands in the readme and I get
 File "/media/TBData/Rita/PyCharm_NERF_kwea/models/rendering.py", line 2, in <module>
    from torchsearchsorted import searchsorted
ImportError: cannot import name 'searchsorted' from 'torchsearchsorted' (unknown location)

**Comment by Borailuce99** [comment]
I had the same problem recently. Searching it on internet I found that the torchsearchsorted is not required anymore. The current version of torch (I use 1.10.0+cu113) already makes what torchsearchsorted does. You just need on models > rendering.py, change "torchsearchsorted" to "torch.searchsorted" and don't import "torchsearchsorted" on the top of the code.

**Comment by kwea123** [comment]
I recommend using the `dev` branch, which already has this change applied.

**Comment by Borailuce99** [comment]
But with that branch, when i try to install the requirements, it appears an ERROR that I can only install torch from 1.7.1 version or newer

**Comment by Borailuce99** [comment]
But now, I can't install torchvision 0.8.2. It shows an error:

ERROR: Could not find a version that satisfies the requirement torchvision==0.8.2 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1)

**Comment by kwea123** [comment]
@Borailuce99 You are right, it seems that torch==1.7.1 and torchvision==0.8.2 has disappeared...
I will try to update to the latest pytorch and pytorch lightning versions recently.

**Comment by Borailuce99** [comment]
I installed both alternatively using the wheels commands from here https://pytorch.org/get-started/previous-versions/ and deleting the lines on the "requirements.txt". Now it works fine with torch==1.7.1+cu110 and torchvision==0.8.2+cu110 ...

**Comment by kwea123** [comment]
I just updated pytorch to the latest version (1.10.0). Now this should be solved.
