### ISSUE TITLE
PSNR of ~30 on lego scene 

### ISSUE THREAD

**Issue by slippylolo** [kwea123/nerf_pl#11]
Hey,

Thank you for this repo. 

You mention successfully reproducing the PSNR of ~30 on the lego scene of the synthetic dataset. Would you be able to provide the configuration you used to do so?

Thanks!

**Comment by kwea123** [comment]
exactly [this](https://github.com/kwea123/nerf_pl/releases/tag/v1.0). Use `eval.py` to compute the psnr.
I did many experiments at the beginning so please tell me if you get a different psnr value.

**Comment by slippylolo** [comment]
Thank you for the prompt answer. 

I just realized this was my mistake. I was looking at the combined PSNR of the fine + coarse model losses. Obviously this would be lower much lower. 

Now that I am looking at the proper metric (PSNR of only one reconstruction), everything makes much more sense.

Thank you for providing details and answering rapidly.
