### ISSUE TITLE
关于optimizers的使用问题

### ISSUE THREAD

**Issue by BoMingZhao** [kwea123/nerf_pl#112]
您好，我想freeze住coarse网络去train fine网络，因此我没有将coarse网络加入到model_to_train中，也就是说coarse没有通过optimizers，但我发现coarse还是会发生改变。所以想请教一下有什么办法freeze住coarse网络吗？十分感谢

**Comment by kwea123** [comment]
你用的是nerfw branch嗎?
正常來說只要把https://github.com/kwea123/nerf_pl/blob/f121fc135dbc75d4edccedfb7d08b58a64fc8c88/train.py#L64 改成`self.models_to_train += [self.nerf_fine]`就可以了，你是這樣做的嗎?

**Comment by BoMingZhao** [comment]
> 你用的是nerfw branch嗎? 正常來說只要把
> 
> https://github.com/kwea123/nerf_pl/blob/f121fc135dbc75d4edccedfb7d08b58a64fc8c88/train.py#L64
> 
> 改成`self.models_to_train += [self.nerf_fine]`就可以了，你是這樣做的嗎?

是的是的，我用的nerfw branch，我写的方法跟您说的一样，但不知为何eval时我发现模型参数似乎更新了

**Comment by kwea123** [comment]
改成这样后理论上coarse是不会更新的啊。。
你是用nerf_coarse.weights来取得各层的参数，然后发现他们改变了吗？

**Comment by BoMingZhao** [comment]
哦哦sorrysorry，我发现bug是什么了，我在后面又init了一遍optimizer，导致又重新把model加进去了。
感谢！
