### ISSUE TITLE
Turn .npy models into .ckpt ones

### ISSUE THREAD

**Issue by AndreaMas** [kwea123/nerf_pl#116]
Hi, I want to use the extract_colored_mesh.py code on my models. 
However, I've used the original nerf repo to train my (custom made) blender scenes.
Therefore, I have my models in model.npy and fine_model.npy format.
Is there a simple way to turn these into model.ckpt?

**Comment by kwea123** [comment]
I'm afraid that you need to do trial & error by yourself. Although I think my model has the same structure as the original one, I think you need to correctly map the weights one to the other. Especially for the positional encoding, you need to make sure the order is the same.
