### ISSUE TITLE
use colmap_colab run in silica data get a error

### ISSUE THREAD

**Issue by Yes-Jumby** [kwea123/nerf_pl#118]
dear auther,
all is same to the demo like you.but get 
![image](https://user-images.githubusercontent.com/51182133/147408153-c6273a17-84c2-4a44-98ee-3536e42036ef.png)

i note in original ipynb,here is the result:
![image](https://user-images.githubusercontent.com/51182133/147408291-1fa56d4d-3ea1-42dd-afc1-8c4bf5e00af5.png)
IImages # 65 while it is 35 in my output
I get 48 imgs from your google driver,maybe the data has difference?

**Comment by Yes-Jumby** [comment]
I check it ,in the video the img is from IMG_E4511 +;
while in my download data set ,it is IMG_E4615.JPG to IMG_E4662JPG;
could you please share the original dataset?

**Comment by teachyourselfcoding** [comment]
I trained using the colmap output provided and it was successful. I tried to run colmap myself using the images from the google drive and I had the same error as you. Do @me if you managed to fix this issue!

**Comment by kwea123** [comment]
Hi, indeed the data in the video is different with what is on the google drive now. I forgot the reason why I retake another dataset, but I have made sure that the data is consistent. The 48-image data is the correct one.
Sometimes COLMAP fails to get the pose for all images (in your case only 35/48 was successful), that makes the `imgs2poses.py` fail. I recommend using my `poses_bounds.npy` directly on the google drive, and you can skip the colmap notebook.

**Comment by teachyourselfcoding** [comment]
I see, any idea why colmap cant find poses for all images?

**Comment by teachyourselfcoding** [comment]
>  colmap每次的結果會有隨機性，所以有時候會失敗。這個只能通過調整參數的方法來試誤。我colab上提供的沒有這個功能，你需要查詢一下相關命令，然後修改colab上的命令才可以
-from your reply elsewhere, thanks!

There is a randomness to the colmap output, which would require adjusting parameters of colmap, which is a feature not available on the colab notebook.
