### ISSUE TITLE
Post Colmap error

### ISSUE THREAD

**Issue by 3ventHoriz0n** [kwea123/nerf_pl#12]
I'm getting the following error:

Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 274, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/content/LLFF/llff/poses/pose_utils.py", line 14, in load_colmap_data
    camdata = read_model.read_cameras_binary(camerasfile)
  File "/content/LLFF/llff/poses/colmap_read_model.py", line 115, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/nerf_pl/mug_for_nerf/sparse/0/cameras.bin'

My input: 59 3024x3024 images
Could you help? Thanks!

**Comment by kwea123** [comment]
Did colmap run successfully? Did you get any output in your data folder?

**Comment by 3ventHoriz0n** [comment]
Yes I got colmap.txt, database.db and the sparse folder was created.

**Comment by kwea123** [comment]
So you have sparse folder but not the file `sparse/0/cameras.bin`? That is weird. Do you see any error message in the colmap.txt?

**Comment by 3ventHoriz0n** [comment]
### The following is the output in Colmap_output.txt under "Loading Database"

Loading cameras... 1 in 0.000s
Loading matches... 1711 in 0.021s
Loading images... 59 in 0.017s (connected 59)
Building correspondence graph... in 0.213s (ignored 0)

Elapsed time: 0.004 [minutes]

  => No good initial image pair found.
  => Relaxing the initialization constraints.
  => No good initial image pair found.
  => Relaxing the initialization constraints.
  => No good initial image pair found.
  => Relaxing the initialization constraints.
  => No good initial image pair found.
  => Relaxing the initialization constraints.
  => No good initial image pair found.

Elapsed time: 0.538 [minutes]

### If you want to take a look at the images go [here](https://drive.google.com/drive/folders/163b0mu8PxHgiz_n-7f-Ni2zxpIOiUOKV?usp=sharing)

**Comment by kwea123** [comment]
Ok the problem is on the images, you should not rotate the object, instead you should walk around the object and take photos from different angles while keeping the object fixed. This is a standard rule and you can find some videos explaining it, for example [this one](https://www.youtube.com/watch?v=1D0EhSi-vvc&t=225s)

**Comment by 3ventHoriz0n** [comment]
Alright thanks!
