### ISSUE TITLE
How can i realize realistic mixed reality photos  in Unity?

### ISSUE THREAD

**Issue by mrlihellohorld** [kwea123/nerf_pl#123]
**Describe the bug**
MixedReality model in unity, I achieved the effect as shown below 
![image](https://user-images.githubusercontent.com/31719207/151118811-c433cfe5-76d2-4bfb-acee-fa2633f70208.png)
Further, I want to replace the sphere with a human cartoon model, like your renderings, with lights, shadows. How do I do it, is it to replace the materials? 
![image](https://user-images.githubusercontent.com/31719207/151111126-6f2e54b4-5066-4677-ac22-f0194331e067.png)

**Screenshots**

**Comment by mrlihellohorld** [comment]
I imported a model, but there are no shadows. Can you help me with this, thanks

![image](https://user-images.githubusercontent.com/31719207/151280412-77a0e320-fc40-4f6c-8f16-5088dde3210b.png)

**Comment by kwea123** [comment]
It is answered in the other thread. Please check there

**Comment by shoutOutYangJie** [comment]
> It is answered in the other thread. Please check there

why don't you use "appearance embedding" for static MLP head?
>  xyz_encoding_final = self.xyz_encoding_final(xyz_)
        dir_encoding_input = torch.cat([xyz_encoding_final, input_dir_a], 1)
        dir_encoding = self.dir_encoding(dir_encoding_input)
        static_rgb = self.static_rgb(dir_encoding) # (B, 3)
        static = torch.cat([static_rgb, static_sigma], 1) # (B, 4)

**Comment by shoutOutYangJie** [comment]
@ do you have wechat? or your email? thanks .
