### ISSUE TITLE
Unity projects

### ISSUE THREAD

**Issue by andybak** [kwea123/nerf_pl#13]
Hi,

I'd love to try out the real time volume rendering example myself. Is it possible to upload the Unity projects somewhere?

**Comment by kwea123** [comment]
Yes, I'm still cleaning the code. Once I finish I will notify you here.

**Comment by kwea123** [comment]
@andybak The project in online now! [here](https://github.com/kwea123/nerf_Unity)
Please know if you encounter any problem or any missing assets (it's my first time uploading a unity project)
Currently you can only play with my data, I will add code to allow you generate your own data (for mixed reality or volume rendering) in the future

**Comment by andybak** [comment]
Looks good at first glance. The top level structure is correct and you're using a sane .gitignore.

I'll post anything I spot in the issues over on that repo. Thanks!

**Comment by kwea123** [comment]
The guidance for generating your own data for mixed reality and volume rendering is [here](https://github.com/kwea123/nerf_pl/blob/master/README_Unity.md)
