### ISSUE TITLE
NeRF-W latent appearance in coarse model

### ISSUE THREAD

**Issue by ricshaw** [kwea123/nerf_pl#130]
Thanks for the code!
Why don't you feed the latent appearance embedding into the coarse NeRF model? Is this a mistake?
In the NeRF in the Wild paper it says:
"Like NeRF, we simultaneously optimize two copies of Fθ: A fine model that uses the model and losses described above, and a coarse model that uses only the latent appearance modeling component."

**Comment by kwea123** [comment]
You're correct I didn't add the appearance encoding to the coarse model, it should be a mistake. Unfortunately changing that now will break my pretrained models, so I will point the reader to that part in the readme.
