### ISSUE TITLE
What does calling self(rays) do?

### ISSUE THREAD

**Issue by exnx** [kwea123/nerf_pl#134]
Hi, I'm new to NeRF, but not new to Python.  However, there's a line in the training code I've never seen before.  Just wondering if anyone can shed some light on what this does?  I didn't know you could call `self` like that.

The line is
`results = self(rays)` in the train and val steps.

and it occurs here:((https://github.com/kwea123/nerf_pl/blob/c5910f84321eb5f72e3332507b0384f1b23f51f7/train.py#L123)
)

Thank you!

**Comment by kwea123** [comment]
This is an usage only valid for `pytorch-lightning` class. Basically it calls the forward function:
https://github.com/kwea123/nerf_pl/blob/c5910f84321eb5f72e3332507b0384f1b23f51f7/train.py#L49
which renders the rays.

**Comment by exnx** [comment]
thanks!
