### ISSUE TITLE
NERFW pose vs w2c 

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [kwea123/nerf_pl#135]
Dear kwea123, 
Thank you for your hard work!

could you please clarify why do you multiply poses by -1 but dont do it for w2c matrix and after that you use w2c for nears/fars estimation? 
![image](https://user-images.githubusercontent.com/22734034/159000658-9a85bc66-8363-4ae0-834f-ad24e3e9522a.png)
![image](https://user-images.githubusercontent.com/22734034/159000791-0e45059c-1080-4f7a-a580-bfb7f28b9d76.png)

**Comment by SrinjaySarkar** [comment]
I am not sure but I believe because that line of code changes the direction of the camera from up and back axis to down and front.

**Comment by kwea123** [comment]
Answer from @SrinjaySarkar is correct. Btw, next time you can create a permanent link to a code snippet so that it's easier to see which part you have question.

**Comment by YaroslavShchekaturov** [comment]
I suppose that the answer is the following: 
when you multiply by -1 you chenge to the opencv convention to opengl convention where z points back.
