### ISSUE TITLE
How to resume the training

### ISSUE THREAD

**Issue by casaucao** [kwea123/nerf_pl#14]
Hi there, thank you very much for this repo. It's very helpful.

I'm using your nerf_colab.ipynb to generate train the model. However, I don't really know how to resume from an existing checkpoint. Please, could you tell me how to resume from an existing checkpoint in order to continue the training? I'm a machinelearning/artificialintelligence newbie.

Thank you for your hard work.

**Comment by kwea123** [comment]
If you're using colab, I'm afraid that it automatically deletes all files once you disconnect, so your models will be lost, unless you manually download the checkpoints from colab.
So did you manually save a checkpoint and want to resume from that? It is simple then, you just need to add the argument `--ckpt_path ${YOUR CHECKPOINT}` to `python train.py`.

**Comment by casaucao** [comment]
Perfect! Yes, I'm downloading every checkpoint in order to save locally and don't lose them if I'm disconnected from colab.

Thank you for your answer!! Really grateful.

Maybe it possible to modify train.py to save ckpt files to GDrive. Anyway, thank you again!

**Comment by kwea123** [comment]
Yes, it is possible, modify this line:
https://github.com/kwea123/nerf_pl/blob/6ea0410768b578209d3704f44baf8dec922db1e6/train.py#L160
change the string `ckpts` to the folder you want to save to, e.g. `/content/drive/My Drive/colab`
It is a really specific case so I prefer not to add this as an argument, but I'll leave it here in case someone has the same need.
