### ISSUE TITLE
Colmap currently does not support spherical (360) images. They are not compatible to the currently available camera models.

### ISSUE THREAD

**Issue by asad-ak** [kwea123/nerf_pl#144]
So I was trying to follow through with tour tutorials and I bumped into a problem where the spherical 360 images did not work on colmap. Colmap was not able to calculate the depths, etc for these images.
So I posted the problem on Colmap initially where I asked them if I need to pass any special arguments or parameters for these calculations for spherical view images and they replied with the subject of this issue which is: 
"**Colmap currently does not support spherical (360) images. They are not compatible to the currently available camera models.**"

So how do I go about doing this since colmap won't calculate the depths (Poses => through LLFF), how do I train these images on the model?

**Comment by kwea123** [comment]
"spherical 360 images" you mean fish-eye camera images or panorama images? Or do you mean the photos are taken in a circular path? Can you share your photos?

I think colmap doesn't support fish-eye camera images or panorama images at the moment, and to my knowledge there still isn't any nerf-related work that tackles these kinds of imagery.

**Comment by asad-ak** [comment]
> "spherical 360 images" you mean fish-eye camera images or panorama images? Or do you mean the photos are taken in a circular path? Can you share your photos?
> 
> I think colmap doesn't support fish-eye camera images or panorama images at the moment, and to my knowledge there still isn't any nerf-related work that tackles these kinds of imagery.

https://drive.google.com/drive/folders/1iF1orUFxTwjH0BRHKfeggq88R5HriwpH?usp=sharing

**Comment by kwea123** [comment]
This is just 360 camera path, so is supported by COLMAP. You can try to run COLMAP like in my tutorial, it should work. However I am not sure if the reconstructed pose will be good, since the mug lacks texture and the background is empty. If you are using synthetic data, I recommend that you recover the ground truth pose directly and use that to train, without passing by COLMAP.

**Comment by asad-ak** [comment]
> This is just 360 camera path, so is supported by COLMAP. You can try to run COLMAP like in my tutorial, it should work. However I am not sure if the reconstructed pose will be good, since the mug lacks texture and the background is empty. If you are using synthetic data, I recommend that you recover the ground truth pose directly and use that to train, without passing by COLMAP.

I followed the exact same tutorial, colmap did not work on it. I will try using a different item now and get back to you if the problem persists.

**Comment by 869299603-tjdtv** [comment]
hi ,i think u can use E2P algorithm to trans 360 images to perspective images .then u can use colmap to generate their poses. 
ps: u need to calculate focal of perspective images ,since translated images do not have exif
