### ISSUE TITLE
clarification for decrease of network layers

### ISSUE THREAD

**Issue by qsobad** [kwea123/nerf_pl#17]
is there any reason to decrease number of layers (from four to one) for dir? 
for speed or the idea of less variation in dir.

`
        # direction encoding layers
        self.dir_encoding = nn.Sequential(
                                nn.Linear(W+in_channels_dir, W//2),
                                nn.ReLU(True))
`

**Comment by kwea123** [comment]
This follows the structure proposed in the paper. The number of layer is actually 1, not 4 which was a mistake. https://github.com/bmild/nerf/issues/11

**Comment by qsobad** [comment]
cool!
