### ISSUE TITLE
Does positive loss/b_l necessary for validity of training nerf-w?

### ISSUE THREAD

**Issue by LongruiDong** [kwea123/nerf_pl#174]
I am training nerf-w on replica data which  contains hardly any transient objects.
The total loss has become negative during first epoch, cause the beta loss `b_l` achieve to around -0.4 quickly.

I notice that you want to make beta to be positive [here](https://github.com/kwea123/nerf_pl/blob/2dd2759619e435c66de48395b115207092967947/losses.py#L44).
I think it might reasonable that beta is quite small as the data is almost static.
From your experience, do you think negative beta values and negative loss values will affect the model training effect?

**Comment by kwea123** [comment]
No, positive or not has no difference. I add some constant to make it positive only in order to use the "log scale" of tensorboard to visualize it better
