### ISSUE TITLE
Overfit on lego

### ISSUE THREAD

**Issue by StarsTesla** [kwea123/nerf_pl#179]
Hi，there！ I tried the code on lego dataset with the recommend config in the readme and keep other config as default, and I found that the situation of training progress: 

train psnr increasing to 20 fastly and then keep growing though, 
val psnr around 10, and floating.

why is that happend?

Hardware:
GPU 3090

Software:
CUDA 11.6
pytorch 12.1
python 3.7.7
pytorch_lighting 1.7.7

I modified the structure of NeRF system with the new pytorch_lighting version(mostly the logger)
I have tired change the softplus for the density activation, increased the batch size, still got not change of the result.

![1665301493262](https://user-images.githubusercontent.com/45264423/194744535-cb468a30-0961-4261-9bf3-7d384381c0cf.png)
 
![1665301790368](https://user-images.githubusercontent.com/45264423/194744595-8d89ab5e-9649-4f4f-950e-6367314b142b.png)

**Comment by StarsTesla** [comment]
It seems I set the white_back = True, set it False make result become normal.

**Comment by YZsZY** [comment]
You know why need to set white_back=True? Thanks a lot!
