### ISSUE TITLE
To generate blender data?

### ISSUE THREAD

**Issue by bell-one** [kwea123/nerf_pl#19]
Hello
i'd like to train model with my 3d models,

I think I can generate blender type data with 3d models(*.obj, *.ply formats)

Is there any codes for do this? 
or do I have to capture every frame and tranforms manually?

**Comment by kwea123** [comment]
you can use `extract_mesh.ipynb` to get .ply file

**Comment by bell-one** [comment]
Thanks for your reply.

I think there is some mistake for my first question..


I would like to know what to do
if I want to generate train data as blender data type 
from 3d data I currently have.

I want to train deep learning model parameters with my own 3d data
like your distribution file 'nerf_synthetic.zip'

Thanks again for your kindness

**Comment by kwea123** [comment]
I have no idea. I think you need to add the original authors [here](https://github.com/bmild/nerf)
