### ISSUE TITLE
About clean the data

### ISSUE THREAD

**Issue by szgy66** [kwea123/nerf_pl#193]
First of all thank you for your great work.
I want to reproduce NeRF_W in my own data set. I know I have to process the data up front. I see your description:
Download the scenes you want from here (train/test splits are only provided for "Brandenburg Gate",  "Sacre Coeur" and "Trevi Fountain", if you want to train on other scenes,  you need to clean the data (Section C) and split the data by yourself)" in **Phototourism dataset**. I think that's the data processing part. But I don't know where this Section C is. Can you help me?

**Comment by 41xu** [comment]
hey do you know where is "Section C"? I have the same questions.

**Comment by WendyeeWang** [comment]
I have the same questions.
