### ISSUE TITLE
Evaluate your training model

### ISSUE THREAD

**Issue by szgy66** [kwea123/nerf_pl#194]
Thank you for your great work!
According to your guidance, I have completed the training the brandenburg data. I follow your orders:
`python prepare_phototourism.py --root_dir ./**/**/brandenburg_gate/ --img_downscale 8 ` and
 `python train.py --root_dir /home/ubuntu/data/IMC-PT/brandenburg_gate/ --dataset_name phototourism --img_downscale 8 --use_cache --N_importance 64 --N_samples 64 --encode_a --encode_t --beta_min 0.03 --N_vocab 1500 --N_emb_xyz 15 --num_epochs 20 --batch_size 1024  --optimizer adam --lr 5e-4 --lr_scheduler cosine --exp_name brandenburg_scale8_nerfw`. I successfully completed the training and saved 20 relevant .ckpt files. When I run the instruction test training model:
`python eval.py --root_dir ./**/**/brandenburg_gate/  --dataset_name phototourism --scene_name brandenburg_test  --split test --N_samples 256 --N_importance 256 --N_vocab 1500 --encode_a --encode_t --ckpt_pat ./**/**/ckpts/brandenburg_scale8_nerfw/epoch=19.ckpt --chunk 16384 --img_wh 320 240` . There is a error:
![image](https://user-images.githubusercontent.com/46223162/218620624-0fd853c0-18fe-4173-9038-7c6781d7b92f.png)
This error also occurs in testing the **scale8_epoch.19.ckpt** model you provided. But when I tested the **scale2_epoch.29.ckpt** you supplied, it worked fine. I don't understand why this is happening, can you help me? Thanks!

**Comment by Linya-Peng** [comment]
Hi!
I‘m facing the same issue. May I know how you fix it?
Thanks!
