### ISSUE TITLE
Why NeRF-W does not support datasets in LLFF form?

### ISSUE THREAD

**Issue by lif314** [kwea123/nerf_pl#196]
![image](https://user-images.githubusercontent.com/63114150/223940886-490f3238-6412-4ef6-9d9f-9e9557f120c5.png)

Thanks!

**Comment by hhhddddddd** [comment]
I have the same problem. Have you solved it?
This question is very important to me. 
Thank you very much! @lif314

**Comment by lif314** [comment]
> I have the same problem. Have you solved it? This question is very important to me. Thank you very much! @lif314

I no longer pay attention to this issue, and I have not implemented this dataloader.
