### ISSUE TITLE
No link to video posted

### ISSUE THREAD

**Issue by leiton** [kwea123/nerf_pl#2]
In the Section COLAB, by the end of the README.md, you say:

> Please see [this video] for the detailed tutorial.

but there is no link to the video. Would you mind to add it? 

Thank you very much! Great work on this repo!

**Comment by kwea123** [comment]
haha the video is not yet made, I plan to make it this weekend, stay tuned!

**Comment by kwea123** [comment]
video posted! It was more than 6 hours of work...
