### ISSUE TITLE
colored mesh using vertex normals

### ISSUE THREAD

**Issue by 3ventHoriz0n** [kwea123/nerf_pl#21]
I read [here](https://github.com/bmild/nerf/issues/44) that you tried the vertex normal method that one of the authors of NeRF suggested but didn't update the code as it didn't work well. Can you please share the code? I would like to give it a shot.

**Comment by kwea123** [comment]
I already included in my code. Add `--use_vertex_normal` argument

**Comment by 3ventHoriz0n** [comment]
Oh sorry, didn't see that.
