### ISSUE TITLE
Colab: extract mesh | installing torchsearchsorted fails

### ISSUE THREAD

**Issue by 3ventHoriz0n** [kwea123/nerf_pl#22]
This is the error:

ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-688c9eye/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-688c9eye/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vcq4akmd/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by kwea123** [comment]
This was due to wrong pytorch version in requirements.txt. It should be fixed now.

**Comment by phongnhhn92** [comment]
Hi, I just wanna ask so if I use the lastest torch version (1.5) then torchsearchsorted doesnt work ?

**Comment by kwea123** [comment]
if you use 1.5 I think you need cuda10.2 installed. I tried torch1.5 with cuda10.1 and it can't compile successfully, but torch1.5(.0) with cuda10.2 works for me.

**Comment by phongnhhn92** [comment]
Yeah seems like it is time for me to upgrade to cuda 10.2 =)))

**Comment by kwea123** [comment]
I upgrade to torch1.6, and the 3rd party `torchsearchsorted` package is not required anymore since it's already included in pytorch natively. Please checkout the branch `torch1.6` with all other packages also upgraded up-to-date.
