### ISSUE TITLE
floating point arithmetic error

### ISSUE THREAD

**Issue by 3ventHoriz0n** [kwea123/nerf_pl#23]
I have a VM on GCP using Tesla t4. I'm trying to run `extract_color_mesh.py`. 
```
xmim, max = -0.40, 0.30
ymin, ymax = -0.40, 0.30
zmin, zmax = -1.30, -0.60
```
I keep getting the error 'the ranges must have the same length!' so I printed the ranges and
```
xrange = 0.7
yrange = 0.7
zrange = 0.7000000000000001
```
??!! 

What do you think is the problem?

**Comment by 3ventHoriz0n** [comment]
I changed the values of ranges. Now the execution gets killed.

**Comment by kwea123** [comment]
I removed the assertion already, please pull and check again

**Comment by 3ventHoriz0n** [comment]
Thanks. I had commented the assertion and checked. The execution gets killed. I will pull and check again. The colab was working but now fails to install torchsearchsorted.
