### ISSUE TITLE
About the unit of the poses_bounds.npy

### ISSUE THREAD

**Issue by dwangxxx** [kwea123/nerf_pl#28]
Hi, thanks for your work! I have a question about the unit of the close and far depth in poses_bounds.npy. Actually, in the fern scene, the near depth is about 17 and the far depth is about 78. Usually, the unit of depth is millimeter, but it seem do not make sense. Beacause the depth of the secen is much larger than 78mm. I don't know why it can work. Can you give me some help? Thank you very much!!!

**Comment by kwea123** [comment]
The unit is not in mm or m, it is scaled such that the minimum distance to the scene is at approximately 1. I think there is no reason you need to tweak the depth, it automatically scales everything to a small range where it works.

**Comment by dwangxxx** [comment]
> The unit is not in mm or m, it is scaled such that the minimum distance to the scene is at approximately 1. For example if the true distance is 3m, then everything is divided by 3. I think there is no reason you need to tweak the depth, it automatically scales everything to a small range where it works.

Thank you!

**Comment by shq12345678** [comment]
Hi, I really want to know the poses_bounds.npy, In fact, I can't find the file called "poses_bounds.npy" in this work. Looking forward to your reply.

**Comment by HannahHaensen** [comment]
@kwea123 so is everything scaled by this depth factor?
