### ISSUE TITLE
apply nerf on interiornet

### ISSUE THREAD

**Issue by ttsesm** [kwea123/nerf_pl#29]
Hi @kwea123,

Thank you for this great work. I wanted to ask you whether do you think that I could use nerf to create the 3D mesh of the scenes from the Interiornet dataset (https://interiornet.org/). The Visim application that they show in their video is not available until now and moreover the provided ground truth, it doesn't seem to fit the renderings. However, they provide some renderings, including depth and albedo maps and thus I was thinking whether nerf could be useful.

**Comment by phongnhhn92** [comment]
Can you provide some images from this dataset ? If we can run colmap on this dataset then I think it might be possible.

**Comment by ttsesm** [comment]
@kwea123 I see, yes I knew that most likely it would not be straight forward.

@phongnhhn92 you can download one scene from the following links:

1. https://drive.google.com/file/d/1FHupJ3nOhXXVibxvNc6Mg__k34_ekOp4/view
2. https://drive.google.com/file/d/1oyXVDVSExPGoPy_AmGCckIMkY0sYJr-Z/view

The first one contains the "ground truth" data and it would look like this:

![image](https://user-images.githubusercontent.com/10189018/88919780-04f9c480-d26c-11ea-86eb-11cb1a0cfde9.png)

where the 3 folder contain the camera information for 3 different renderings and the .xml files contain the scene information with two different lighting modes. I've tried to parse the .xml file in order to extract the 3D mesh of the scene but it seems that the output is not the same as in the rendered images if you check below.

The second link contains 3 different renderings for each lighting mode (i.e. original, random):

![image](https://user-images.githubusercontent.com/10189018/88919698-ded42480-d26b-11ea-903a-2ced3c766766.png)

inside you will find the images for each rendered map, e.g. albedo, pinhole cam, fish-eye cam, depth, etc...

![image](https://user-images.githubusercontent.com/10189018/88919723-ef849a80-d26b-11ea-8cbe-8e2270053dea.png)

Now I was thinking that by loading the images from "cam" together with "depth" I should be able somehow to extract the 3D point cloud/mesh of the scene. I've tried it with open3d but the output was not good. I did not try colmap though.

Let me know if you have any other question.

**Comment by kwea123** [comment]
If you can successfully convert the poses to adapt to these complex trajectories, it would be really helpful. Please let us know if you manage to do so.

**Comment by ttsesm** [comment]
@kwea123 what do you mean with "convert the poses to adapt to these complex trajectories" 

In the ground truth folder they provide the camera poses as following:

```
#timestamp [ns], position.x [m], position.y [m], position.z [m], quaternion.w [], quaternion.x [], quaternion.y [], quaternion.z []
0000000000031666668,0.303582847,-3.14995146,1.31473804,0.604126871,0.677215457,-0.313424408,-0.279597998
```

I've also tried to load the images to Colmap, but the output does not seem that consistent as you can see below:

![image](https://user-images.githubusercontent.com/10189018/89161653-3081f500-d573-11ea-9a58-e21936e3fa1c.png)

**Comment by kwea123** [comment]
![image](https://user-images.githubusercontent.com/11364490/89169858-c80a3680-d5b9-11ea-82af-30f81719ff20.png)
Like I draw here, suppose blue objects are the scene objects and black points is the trajectory, you need to convert the poses such that the center is the scene center (red star) and the bounds are approximately from -1 to 1. By default I think the pose center could be anywhere, that doesn't work for nerf.

**Comment by ttsesm** [comment]
I see, hmm it doesn't seem to be straight forward. I'll check if I can do anything though.

**Comment by ttsesm** [comment]
apparently the follow up work https://nerf-w.github.io/ would be able to handle my case scenario :-)

**Comment by kwea123** [comment]
Yes, I'd also like to know the trick that they use to convert the poses. It doesn't seem that they'll open source though...
