### ISSUE TITLE
NDC coordinate

### ISSUE THREAD

**Issue by dwangxxx** [kwea123/nerf_pl#30]
Hello, thanks for your apply for the previous issue. Now I have another question. Assume that we have two photos obtained by two different camera pose and one point in photo 1 and one point in photo 2 will reproject to the same 3D coordinate (the same world coordinate) . But these two points will be transformed to NDC coordinate. I want to know if these two points have the same coordinate after NDC transformation. I think if NDC works, they may have the same coordinate after NDC transformation. Could you provide me some information? Thank you!!!

**Comment by kwea123** [comment]
If they have the same 3d coordinate, they will have the same ndc coordinate. The transformation is 1 to 1.

**Comment by dwangxxx** [comment]
> If they have the same 3d coordinate, they will have the same ndc coordinate. The transformation is 1 to 1. The exact formula can be found in the pdf here [bmild/nerf#18](https://github.com/bmild/nerf/issues/18)

Thanks for you quick reply! I want to know that can we apply ndc transformation for synthetic data such as the lego dataset. If it is possible, what can I do for that? Thank you.

**Comment by kwea123** [comment]
Please see that issue for when to use ndc coordinate. It is not optimal to apply it for every scene; it should only be applied when the scene is forward-facing. For 360 scenes it should not be applied.

**Comment by dwangxxx** [comment]
> Please see that issue for when to use ndc coordinate. It is not optimal to apply it for every scene; it should only be applied when the scene is forward-facing. For 360 scenes it should not be applied.
Sorry for that. I see. Thank you.
