### ISSUE TITLE
Groudtruth camera poses instead of COLMAP?

### ISSUE THREAD

**Issue by xbw1266** [kwea123/nerf_pl#32]
@kwea123 Thanks for the great work! However, my dataset has precise camera poses attached to each RGB image. Is there any way I can use the external camera poses to generate my training set? Thanks.

**Comment by kwea123** [comment]
You just need to rewrite the part where the dataloader loads the poses and the bounds:
https://github.com/kwea123/nerf_pl/blob/c739e49cc5d20cde51a876a96c1298948abe07bb/datasets/llff.py#L177-L211
I suggest that you create a new class.

**Comment by xbw1266** [comment]
Thanks for your suggestions! I'll give it a try.

**Comment by zeyu-hello** [comment]
@xbw1266 hello I have same problem, do you figure out how to deal with it?
