### ISSUE TITLE
COLMAP Error : Mismatch

### ISSUE THREAD

**Issue by theCodes7** [kwea123/nerf_pl#33]
Hello,
I have created my dataset and trying to train and test it. 
I get following error when I run 360 inward-facing scene.
AssertionError: Mismatch between number of images and number of poses! Please rerun COLMAP!
In my dataset, there are 45 images however when I run COLMAP, it detects 14 images only but in the colmap_output.txt it shows details of 45 images. 

O/P of running COLMAP cell
Post-colmap
Cameras 5
Images # 14
Points (1918, 3) Visibility (1918, 14)
Depth stats 9.552434898035012 42.84922232367337 17.069477140501178
Done with imgs2poses

What could be the reason ?How should I try to run on my dataset?

**Comment by kwea123** [comment]
I think you need to check your images, make sure they are not too dark/bright, contain enough feature points, and the poses between images shouldn't change too much. 
Are you running COLMAP with GUI? If so you can check the number of successfully reconstructed images in the gui.

If you are able to rewrite the code, you can try to only extract successful images (14 out of 45 in your example) and use them to train, it is a little more complicated than re-taking clean photos in my opinion though.

**Comment by theCodes7** [comment]
I tried a clean dataset and it worked. Thanks!
