### ISSUE TITLE
ImportError: cannot import name 'searchsorted'

### ISSUE THREAD

**Issue by theCodes7** [kwea123/nerf_pl#34]
When I tried running it on my hardware (not in colab) using conda: 
after running
python train.py \
   --dataset_name llff \
   --root_dir $LLFF_DIR \
   --N_importance 64 --img_wh 504 378 \
   --num_epochs 30 --batch_size 1024 \
   --optimizer adam --lr 5e-4 \
   --lr_scheduler steplr --decay_step 10 20 --decay_gamma 0.5 \
   --exp_name exp 
I got the following error.
ImportError: cannot import name 'searchsorted'

I am trying to run on own dataset.

**Comment by kwea123** [comment]
Did you do the final step https://github.com/kwea123/nerf_pl#software?

**Comment by theCodes7** [comment]
When I run pip install .
I get this :  
6 errors detected in the compilation of "/tmp/tmpxft_00002992_00000000-6_searchsorted_cuda_kernel.cpp1.ii".
  error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torchsearchsorted

**Comment by kwea123** [comment]
It currently only supports CUDA>10.1. You can try branch `torch1.6` to see if the native pytorch version supports cuda 9.0. It's not guaranteed
