### ISSUE TITLE
Strange gif output from eval.py

### ISSUE THREAD

**Issue by herksaw** [kwea123/nerf_pl#35]
Hi, first of all thanks for this great work! So far I have tried to play with this for few days, and I noticed that the result came out from evaluation code always produced a strangely 'messed' gif?

For example here is a screenshot of the gif output from silica model that posted on release section:

![image](https://user-images.githubusercontent.com/2655050/93657943-949c4200-fa69-11ea-8c98-9c11187fcdff.png)

Is this normal? Or did I missed any steps?

**Comment by kwea123** [comment]
please post the full command you use.

**Comment by herksaw** [comment]
Posted as below:

![image](https://user-images.githubusercontent.com/2655050/93660232-25c9e380-fa7f-11ea-967c-1264896c65a6.png)

Despite of this strange output, the colored mesh can be extracted without any problems, and it looked good too.

**Comment by kwea123** [comment]
You need to add `--spheric_poses` argument. https://github.com/kwea123/nerf_pl#mag_right-testing

**Comment by herksaw** [comment]
Thanks! Just tested and it worked great! :D

**Comment by ThisIsIsaac** [comment]
Maybe stating that explicitly in the [release](https://github.com/kwea123/nerf_pl/releases) make it clearer for others trying to run eval.py. I had the same trouble because I didn't know I had to put `--spheric_poses`

**Comment by kwea123** [comment]
Thanks for pointing out. I updated the release.
