### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by theCodes7** [kwea123/nerf_pl#38]
Got the error after running this on own dataset.
python train.py \
   --dataset_name llff \
   --root_dir $DIR  \
   --N_importance 64 --img_wh 504 378 \
 --spheric --use_disp \
   --num_epochs 30 --batch_size 1024 \
   --optimizer adam --lr 5e-4 \
   --lr_scheduler steplr --decay_step 10 20 --decay_gamma 0.5 \
   --exp_name exp

RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

**Comment by kwea123** [comment]
Try to remove `--use_disp`. I didn't look into the reason, but it seems sometimes it results in division by zero.

**Comment by theCodes7** [comment]
Validation sanity check: 0it [00:00, ?it/s]/pytorch/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [5,0,0], thread: [32,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/pytorch/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [5,0,0], thread: [34,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.


Traceback (most recent call last):
  File "train.py", line 181, in <module>
    trainer.fit(system)

I think error is something related to image size, not sure though.
