### ISSUE TITLE
no siftgpu supported error!

### ISSUE THREAD

**Issue by visonpon** [kwea123/nerf_pl#40]
Hi, @kwea123, thanks for your wonderful work. when I use `colmap_colab.ipynb` as you described, I meet the  error when executing `images2pose.py`, hope you can give some advice, thanks~

**Comment by kwea123** [comment]
can you post the command and the whole output?

**Comment by visonpon** [comment]
```
cd /content/LLFF
!python imgs2poses.py "/content/drive/My Drive/data/
```
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
...
ERROR: SiftGPU not fully supported.
    @     0x7f59cc94a8a0 (unknown)
    @     0x7f59cb60bf47 gsignal
    @     0x7f59cb60d8b1 abort
    @     0x7f59cc22f957 (unknown)
    @     0x7f59cc235ae6 (unknown)
    @     0x7f59cc235b21 std::terminate()
    @     0x559bf32e1387 (unknown)
    @     0x559bf32235d0 (unknown)
    @     0x559bf31dbfae (unknown)
    @     0x559bf31bc5ee (unknown)
    @     0x7f59cb5eeb97 __libc_start_main
    @     0x559bf31c620a (unknown)
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/content/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/content/drive/My Drive/jc/database.db', '--image_path', '/content/drive/My Drive/jc/images', '--ImageReader.single_camera', '1']' died with <Signals.SIGABRT: 6>.

**Comment by visonpon** [comment]
Hi @kwea123 I have solved this problem by setting` '--SiftExtraction.use_gpu', '0'` so that the feature extraction is based on CPU

**Comment by kwea123** [comment]
I think gpu is by default enabled in the colab, but glad you solved the first problem.
Can you check if the sparse folder exists after the reconstruction? (under `/content/drive/My Drive/data/`) If not I think the reconstruction didn't succeed.
