### ISSUE TITLE
Buffered data was truncated after..

### ISSUE THREAD

**Issue by SofiaMustafina** [kwea123/nerf_pl#42]
I train my model for 30 epochs.
After the 13th epoch, the program crashes.
The program displays the following message: 
![QwjcCE2-XA8](https://user-images.githubusercontent.com/32891678/97803502-c1986300-1c6b-11eb-8160-cabd44452654.jpg)

**Comment by kwea123** [comment]
Seems to be a problem of colab. See [here](https://stackoverflow.com/questions/51463383/buffered-data-was-truncated-after-reaching-the-output-size-limit)
