### ISSUE TITLE
extract_color_mesh problem

### ISSUE THREAD

**Issue by ai1361720220000** [kwea123/nerf_pl#44]
你好，我在尝试了你的工程训练好模型后，运行marching_cubes构建出来的mesh会出现很多层地面，同时添加颜色后的模型也不是真实的颜色。
![image](https://user-images.githubusercontent.com/24642194/99144537-99fcbe00-26a1-11eb-9523-9d8cd05d69a1.png)

**Comment by ai1361720220000** [comment]
我添加“use_vertex_normal”参数后就可以了，这是什么原因呢？然而地板出现很多层仍然没有解决

**Comment by kwea123** [comment]
正常來說不加use_vertex_normal也可以的，你可以分享你的data? image, pose跟訓練好的model
地板出現很多層是沒辦法的，這個只能靠手動調整range把下面卡掉

**Comment by ai1361720220000** [comment]
好的，我把我的文件（图片/pose/model）分享给你，麻烦你帮我看一下。https://drive.google.com/drive/folders/1ZWt_-T-rl-BDgkN2YP4oF2iAo42q6HUR?usp=sharing

**Comment by kwea123** [comment]
我調整range為
```
xmin, xmax = -0.5, 0.6 # left/right range
ymin, ymax = -0.5, 0.6 # forward/backward range
zmin, zmax = -2., -0.9 # up/down range
sigma_threshold = 5.
```
之後沒有問題，不用use_vertex_normal。生成的mesh如下
![Screenshot from 2021-01-21 16-35-33](https://user-images.githubusercontent.com/11364490/105318325-b7e92080-5c06-11eb-8e56-db5ea1e6e42b.png)
我傳到你上面的google drive了。

我猜是因為你range沒調好使的地板佔據太大，在remove noise的時候反而只留下了地板。
