### ISSUE TITLE
is torch1.6 branch still under development?

### ISSUE THREAD

**Issue by NIRVANALAN** [kwea123/nerf_pl#47]
Hi! torch1.6 branch seems not working now using the training script privided. As PyTorch has provided searchsorted API in v1.6, will it be merged into master later on?

**Comment by NIRVANALAN** [comment]
no ```normals_ndc_fine``` key in input list under current branch now.

**Comment by kwea123** [comment]
To support the old colab files, the master branch will not be updated.
I did some update (update library versions, remove torchsearchsorted) into the `dev` branch just now. In the future that branch will contain the latest code (might not be updated so often though...)

**Comment by kwea123** [comment]
By the way, `normal` branch is just my personal experiments to try to output the normal map (the result doesn't seem good...), it will not be included anywhere.
