### ISSUE TITLE
Attempt to visualize 3D point cloud of ray termination - poor geometry results on real-world data

### ISSUE THREAD

**Issue by dukeeagle** [kwea123/nerf_pl#48]
Thanks for all the hard work on this!

# Issue
My goal is to use NeRF to extract a 3D point cloud from my trained NeRF model on custom data. I believe I've achieved this on sample data, but I've found that my custom data that uses COLMAP for camera pose estimation gives very poor results. **Is this a consequence of NeRF's poor geometry estimation with imperfect data, or is there a problem with my 3D point estimation?**

### Approach
I found the 3D points of all estimated ray depths while running NeRF in evaluation mode. I appended the results dictionary with these points in [`models/rendering.py`](https://github.com/kwea123/nerf_pl/blob/master/models/rendering.py#L241) via the following:
```python
depth_points = rays_o + rays_d * depth_fine.unsqueeze(1) # 3D point cloud of depth point for each ray 
result['rgb_fine'] = rgb_fine
result['depth_fine'] = depth_fine
result['depth_points'] = depth_points
```
I then collected all 3D points for each frame and combined them to visualize a single point cloud. This went well on my vanilla data, but not on my custom data.

## 3D point cloud of vanilla data
Here's my rendering of a point cloud of the canonical Lego bulldozer example:
![r_19](https://user-images.githubusercontent.com/10426513/102676791-ce620f00-4164-11eb-9b16-914d0bd98be7.png)
 *converts to...*
![Screenshot from 2020-12-17 11-30-22](https://user-images.githubusercontent.com/10426513/102676710-7fb47500-4164-11eb-8ed0-09b5ab3fd329.png)
![Screenshot from 2020-12-17 11-36-31](https://user-images.githubusercontent.com/10426513/102676754-a83c6f00-4164-11eb-99e3-eec125171b66.png)
There's lots of noise, but this can be easily filtered out. Here's a look at the same approach to when I use custom data on a basic chair, with the exception that **the camera extrinsics are fully estimated by COLMAP**, unlike the perfect camera pose data in the example blender files:
## 3D point cloud of custom data
![Screenshot from 2020-12-18 18-04-23](https://user-images.githubusercontent.com/10426513/102676877-403a5880-4165-11eb-9b51-6716817e2ef7.png)
![chair-depth (1)](https://user-images.githubusercontent.com/10426513/102677031-074eb380-4166-11eb-93c7-bfc7c8054be5.gif)

## Summary
As you can see, NeRF has clearly failed to recreate the geometry of my scene despite the appearance being quite good in 2D form. My question is this: **is there an issue with my 3D visualization approach, or is this a consequence of flawed, real-world COLMAP data?** If it's the later, do you have any recommendations for improving my own data collection and processing? [You seemed to be able to recreate your own mesh quite well](https://user-images.githubusercontent.com/11364490/80813184-83f74680-8c04-11ea-8606-40580f753355.png), and I wonder if there are some data capture / COLMAP tips I don't know about.

**Comment by kwea123** [comment]
Hi, the depth image looks good. I think the depth conversion is not good.
This formula `depth_points = rays_o + rays_d * depth_fine.unsqueeze(1)` is correct if the scene is in real coordinate. However, telling from your training images, I suppose you're using NDC (front-facing) to train. In this case, the depth (and `rays_o, rays_d`) in the code is not real depth, you need to apply `depth_real = 1/(1-depth_ndc)` to get real depth (cf. #45) , and use `K^-1 * d * (x y 1)` to backproject the points in real space. I have tested the point cloud fusion in this case and it worked well too. (cf https://github.com/bmild/nerf/issues/35).

To fuse different points from different images, I use MVSNet techniques to filter noisy points (of course you can use your own method).

**Comment by sakshamjindal** [comment]
@kwea123 Could you please update your point cloud fusion code as described in the [issue](https://github.com/bmild/nerf/issues/35#issuecomment-622963055) on bmild's repo.
