### ISSUE TITLE
(nerf_pl) w3c@24g-gpu:~/docker/nerf_pl-master/torchsearchsorted$ pip install .

### ISSUE THREAD

**Issue by stone100010** [kwea123/nerf_pl#5]
/anaconda3/envs/nerf_pl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zwt/docker/nerf_pl-master/torchsearchsorted/setup.py'"'"'; __file__='"'"'/home/zwt/docker/nerf_pl-master/torchsearchsorted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5a3a2zq6/install-record.txt --single-version-externally-managed --compile --install-headers /home/zwt/anaconda3/envs/nerf_pl/include/python3.6m/torchsearchsorted Check the logs for full command output.

**Comment by kwea123** [comment]
What is the problem?

**Comment by stone100010** [comment]
No problem. I've tried several times. Thank you O(∩_∩)O
