### ISSUE TITLE
Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by JustinTChen** [kwea123/nerf_pl#57]
<img width="1222" alt="Screen Shot 2021-02-07 at 1 19 50 PM" src="https://user-images.githubusercontent.com/44789251/107159803-2b00cf80-6947-11eb-9d5d-f478bb965883.png">

Is this a problem with the dataset itself?

**Comment by kwea123** [comment]
Please post the full command and the data you use
