### ISSUE TITLE
loss nerf_synthetic/lego/poses_bounds.npy

### ISSUE THREAD

**Issue by stone100010** [kwea123/nerf_pl#6]
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/docker/nerf_pl-master/data/nerf_example_data/nerf_synthetic/lego/poses_bounds.npy'

**Comment by kwea123** [comment]
what is your command?
Just copy and paste (change `root_dir`)
```
python train.py \
   --dataset_name blender \
   --root_dir $BLENDER_DIR \
   --N_importance 64 --img_wh 400 400 --noise_std 0 \
   --num_epochs 16 --batch_size 1024 \
   --optimizer adam --lr 5e-4 \
   --lr_scheduler steplr --decay_step 2 4 8 --decay_gamma 0.5 \
   --exp_name exp
```
you need to set `dataset_name` to `blender`. I suspect that you set as `llff`.
