### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by jerrysheen** [kwea123/nerf_pl#61]
Hi kwea123, 

when I try to run eval.py, after it generates 15 pictures, the error shows.

I'm running my program on ubuntu 20.04, RTX 2070 mobile (8gb)

and I use 35 pictures (res = 4032 * 3024) as traning data and try to generate resolution = (1008 * 756) pictures.

I think the error is caused by too high resolution for the result images.

Can you help me to fix this problem ? thanks!

`RuntimeError: CUDA out of memory. Tried to allocate 1.69 GiB (GPU 0; 7.79 GiB total capacity; 1.62 GiB already allocated; 704.56 MiB free; 5.88 GiB reserved in total by PyTorch)
`

**Comment by kwea123** [comment]
Yes, your suspect is correct. You can move the rendered chunks to cpu each time to save gpu memory.
More concretely,
set this
https://github.com/kwea123/nerf_pl/blob/422ce4bf5755aec5ca7ff4b24868b21f03145e37/eval.py#L81
to 
`results[k] += [v.cpu()]`
I will update it to be the default code.
