### ISSUE TITLE
After got the model, hwo can I generate a certain view of image by the model?

### ISSUE THREAD

**Issue by jerrysheen** [kwea123/nerf_pl#62]
Hi kwea123, I just wonder is it possible to define a certain view (Lets say spatial location (x,y,z) and viewing direction (θ,φ) ) and generate a image for this view by the nerf_pl model?
Could you please help me with this? thanks!

**Comment by kwea123** [comment]
Of coarse, you can set the testing pose whatever you want. I'll explain for llff dataset, but it's the same for blender.
1. Define (overwrite) the testing pose in `datasets/llff.py`:
 https://github.com/kwea123/nerf_pl/blob/82ce454a5b1acf05a82492d42e9bdae97accf761/datasets/llff.py#L259-L270
    You need the camera's spatial location (x,y,z) and its rotation in a 3x3 matrix.
2. For viewing angle, by default it's the camera's rotation already, but if you want to change it like the specular effect shown in nerf, you can pass a keyword argument `view_dir` to `render_rays` function
   https://github.com/kwea123/nerf_pl/blob/82ce454a5b1acf05a82492d42e9bdae97accf761/models/rendering.py#L171
   and it will take that angle as the render angle, independent of the camera pose.

**Comment by jerrysheen** [comment]
Hi, Thanks for your replies... Sorry I'm busy last week,(because of my hw...)

So basically I know what's going on for this part. by modifying the code you've provided, I can now change the camera position.

Another question is that, How can I know the exactly front side of the model? (seems a little bit hard for me since I feel like all the pictures are taken from the arbitrary position so It's hard to define the front side ..)

maybe Should I check the poses_bound.py and decide on a picture to be the center picture? By using its camera position data?

**Comment by kwea123** [comment]
The front side is the negative z axis if your data is forward-facing, for 360 data there is no "front side."

> maybe Should I check the poses_bound.py and decide on a picture to be the center picture? By using its camera position data?
I don't understand this question. If you want to select the most centered picture, it's the picture whose pose (translation) is closest to zero.

**Comment by jerrysheen** [comment]
![2021-03-12 183625(1)](https://user-images.githubusercontent.com/19220015/110928771-35f1ba00-8362-11eb-8616-790e4c2845d0.png)

for example, I got a model and now I want the camera move horizontally, (like what I show in the picture). Can you tell my how I modify the code? And what else data I need to know.. thanks!

**Comment by kwea123** [comment]
For example you can set the pose to the same of the training poses: `self.poses_test = self.poses.copy()` then you can move its translation, e.g. `self.poses_test[0, 0, 3] += 0.1`. If that's not the correct axis, just try another: `self.poses_test[0, 1, 3] += 0.1` or `self.poses_test[0, 2, 3] += 0.1`. This should be very straightforward if you read the paper and the code carefully.

**Comment by jerrysheen** [comment]
> For example you can set the pose to the same of the training poses: `self.poses_test = self.poses.copy()` then you can move its translation, e.g. `self.poses_test[0, 0, 3] += 0.1`. If that's not the correct axis, just try another: `self.poses_test[0, 1, 3] += 0.1` or `self.poses_test[0, 2, 3] += 0.1`. This should be very straightforward if you read the paper and the code carefully.

thanks! I'll try it
