### ISSUE TITLE
why rotate matrix permute on last axis?

### ISSUE THREAD

**Issue by zjjMaiMai** [kwea123/nerf_pl#64]
sorry for open new issue, cause i can't reopen this https://github.com/kwea123/nerf_pl/issues/63#issuecomment-792545216.

> poses have shape (N_images, 3, 4), we want to permute its rotation axes, so we change axis=2 (last axis).  

i cant understand why shound we change last axis but not first axis. if we have a rotation matrix R_rdf form [**right down front**], and we need change to R_rub form [**right up back**]. we need flip Y-axis and Z-axis like this:
``` python
R_rub = np.diag([1, -1, -1]) @ R_rdf
# same as : R_rub = np.concatenate([R_rdf[0:1, ...], -R_rdf[1:3, ...]], axis=0)
```

**Comment by kwea123** [comment]
I'm afraid that this is not relevant to my code anymore. It seems like a more fundamental tensor operation question. I think it's better to ask on stackflow if you still have question.

As I said in the comment, poses have shape (N_images, 3, 4), so the first axis (N_images) corresponds to each image, i.e. each image has a (3, 4) pose matrix (rotation 3x3 + translation 3x1).
Next, the second axis is the 3 rows of each pose matrix, which doesn't have explicit meaning.
Finally the last axis is the 4 columns of each pose matrix, more precisely, the first column is the camera x axis in world coordinate, the second column y, the third column z, and the fourth column is the camera center.
Therefore, if we want to change the xyz order, we permute this axis, which is the last axis.
