### ISSUE TITLE
given a 2D RGB image that contains a bike, how can I 3d lift the mesh of the bike?

### ISSUE THREAD

**Issue by monacv** [kwea123/nerf_pl#66]
I am interested in 3D lifting of certain objects in a 2D RGB image. Could you please guide me how I can do that using your repo?

**Comment by kwea123** [comment]
nerf is not able to reconstruct 3d given only a single image. maybe [this](https://github.com/nywang16/Pixel2Mesh) helps. I do not know much about this field.
