### ISSUE TITLE
Try to generate high resolution pictures but failed.

### ISSUE THREAD

**Issue by jerrysheen** [kwea123/nerf_pl#67]
Hi kwea123,

when I try to use 4032 * 3024 original pictures to generate 1512 * 1134 pictures.
The lose / val/ train becomes to nan.

![Screenshot from 2021-03-17 21-01-27](https://user-images.githubusercontent.com/19220015/111856099-786b5600-8963-11eb-9475-b0ff0428107f.png)

And there is no ckpt file generated after these parameters went to nan.

When I try the final result. It can only generate a black image.
Can  you help me to figure out where is wrong? Did I use too high resolutions?
Thanks

**Comment by kwea123** [comment]
Hi, the code can handle any resolution theoretically, I have trained once high resolution without problem. The model trains to epoch17, so I assume early epochs don't have problem? Do you have the log until the 16th epoch, and how does the model perform at that point?

**Comment by jerrysheen** [comment]
> the log until the 16th epoch, and how does the model perform at that point?

Hi, I think I solved the problem maybe. I think that's because I took the photos vertically, but the original model treats the images only horizontally? (And I can only set the parameter as 1512 1134 instead of 1134 1512. )   When I took images horizontally, the result is good.
