### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by tiexuedanxin** [kwea123/nerf_pl#68]
**Describe the bug**

**Which branch you use**
Only issues of the *dev* and *nerfw* branches will be considered currently!

**To Reproduce**

**Screenshots**

hello, could you share your data about the Silica GGo figure.

**Comment by kwea123** [comment]
https://github.com/kwea123/nerf_pl/releases/tag/v2.0.1

**Comment by tiexuedanxin** [comment]
> https://github.com/kwea123/nerf_pl/releases/tag/v2.0.1

hello, I find the image number is 65, but there is only 48. Is there some image loss. when i run colmap, it tells me can't get the correct camera pose. Besides there have some modification of nerf such pixelnerf, have you try these method. Finally is there someway to improve texture details for extracted mesh. Very thanks for your work.

**Comment by kwea123** [comment]
Hi, I did several silica experiments, so I might be sharing the wrong data. The 48-image version is the correct one. Where did you find the 65 image number?
For texture details for extracted mesh. The current method can be improved by #37 , maybe you can wait for their code release (I don't know if they will though). I am focusing on other things now. There are too many excellent NeRF-related works now.

**Comment by tiexuedanxin** [comment]
> Hi, I did several silica experiments, so I might be sharing the wrong data. The 48-image version is the correct one. Where did you find the 65 image number?
> For texture details for extracted mesh. The current method can be improved by #37 , maybe you can wait for their code release (I don't know if they will though). I am focusing on other things now. There are too many excellent NeRF-related works now.

hello, is there someway to improve the mesh quality, I find that the mesh extracted from nerf is not very perfect.
