### ISSUE TITLE
make dataset.

### ISSUE THREAD

**Issue by tiexuedanxin** [kwea123/nerf_pl#69]
**Describe the bug**

**Which branch you use**
Only issues of the *dev* and *nerfw* branches will be considered currently!

**To Reproduce**

**Screenshots**

hello, I see that you place the Silica on  the bed and move camera to capture image with iphone, I have a question that if fix the camera location and adjust the Silica pose to capture image, can this setting work correctly.

**Comment by kwea123** [comment]
It's generally not recommended to move the object. It's better to fix the object and move the camera around. You can check general **photogrammetry guidelines** for taking good pictures.
