### ISSUE TITLE
How to make depth maps from 3D representation

### ISSUE THREAD

**Issue by ThisIsIsaac** [kwea123/nerf_pl#70]
How may I create depth maps (as seen in examples below) from the 3D representations? 
![download](https://user-images.githubusercontent.com/49523965/113562759-a332fb00-9641-11eb-8fe3-cfb1998470a2.jpeg)

**Comment by kwea123** [comment]
for each pose, the output already contains the depth (in NDC space, to convert to real space you need to do 1/(1-d) to convert to camera space). You can see [test.ipynb](https://github.com/kwea123/nerf_pl/blob/master/test.ipynb) for an example.

**Comment by ThisIsIsaac** [comment]
@kwea123 Thanks for the reply! I see, so if we use the NDC space, then $$\frac{1}{1-d}$$ where $$d$$ is the depth should work. 
It seems like we only use the NDC space if we don't use spheric poes :

```
                if not self.spheric_poses:
                    near, far = 0, 1
                    rays_o, rays_d = get_ndc_rays(self.img_wh[1], self.img_wh[0],
                                                  self.focal, 1.0, rays_o, rays_d)
 ```

So is there another way to convert the depth if we do use spheric poses?

**Comment by kwea123** [comment]
If using spheric pose, `d` is directly the true depth.
