### ISSUE TITLE
All the values in viewdirs are zero in extract_mesh.ipynb

### ISSUE THREAD

**Issue by SteveSZF** [kwea123/nerf_pl#71]
Hi, thank you for your great work. I found that the values in viewdirs are not all zeros during training and testing. But all the values in viewdirs are zero in extract_mesh.ipynb. Could you explain it? Thank you!

**Comment by kwea123** [comment]
this is because to extract mesh, we only need the occupancy (sigma) and not the rgb colors. Therefore any value of viewdir is fine (it doesn't change the result). Or you can even remove these lines by querying the sigma part only.
