### ISSUE TITLE
Depth Scale after volume rendering

### ISSUE THREAD

**Issue by sakshamjindal** [kwea123/nerf_pl#78]
The depth map values that are obtained from volume rendering lies in between 0 and 1. Are these depth values in the NDC coordinates (non-linear) or camera coordinate system (linear scale). Also, if it is in NDC coordinate system, does do the depth values lie between near plane and far plane. In other words, does the origin lie at the camera or intersection of ray with the near plane (or z = -n)

**Comment by kwea123** [comment]
the depth is the depth from the point to "camera origin". In your words "origin lie at the camera or intersection" not the near plane.
