### ISSUE TITLE
why sample t0 linearly from 0 to 1 in order to get a linear sampling in disparity

### ISSUE THREAD

**Issue by shuochen365** [kwea123/nerf_pl#79]
I can understand the paper moving the camera position origin to the z = -n plane.

> t = -(near + rays_o[..., 2]) / rays_d[..., 2]

> rays_o = rays_o + t[..., None] * rays_d

But I don't understand why t0 changes linearly from 0 to 1 in NDC space. Because according to the formula, it should be - 1 to 1.

**Comment by kwea123** [comment]
After moving `o` to the near plane, `t=0` corresponds to `z=-1` in NDC space, and `t=1` corresponds to `z=1`. You can run the code to see it if you still don't understand the formula.

**Comment by shuochen365** [comment]
Ok,Thank you very much
