### ISSUE TITLE
nerf-w custom dataset

### ISSUE THREAD

**Issue by FurKan7** [kwea123/nerf_pl#81]
Hello, I would like to try nerf-w with custom dataset but i do not understand how to create dataset like phototourism dataset?

Thanks.

**Comment by kwea123** [comment]
Hi, you only need to create a new dataset script following [phototourism.py](https://github.com/kwea123/nerf_pl/blob/nerfw/datasets/phototourism.py). First you run COLMAP on the input images to get the poses, then just follow the template to create a dataset class that yields data for training. There are other small modifications to make in `train.py` and `opt.py` to parse your dataset class, but other than that you don't need to worry about anything like the model or loss.

**Comment by FurKan7** [comment]
Hi, colmap just write only 1 camera into cameras.bin file. Therefore when i run phototourism.py, i saw only one camera then occurs an error.

P.S. When i run nerf_pl training code i just take result which is very good. But for nerf-w i faced cameras.bin file problem

**Comment by NeverlandCookies** [comment]
Hello, I am also working on training NeRF-W on custom dataset. Did you succeed in doing so?

**Comment by cfeng16** [comment]
Also facing camera issues

**Comment by ShineiArakawa** [comment]
I think there might be an issue with the line "cam = camdata[id_]" at [line 78 in phototourism.py](https://github.com/kwea123/nerf_pl/blob/2dd2759619e435c66de48395b115207092967947/datasets/phototourism.py#L78). According to the [COLMAP reference](https://colmap.github.io/format.html#cameras-txt), it might be necessary to select the camera through the value of "CAMERA_ID" assigned to each image in `images.bin`. I apologize if I'm mistaken.
