### ISSUE TITLE
About beta in NeRF-w

### ISSUE THREAD

**Issue by xingranzh** [kwea123/nerf_pl#83]
Hello there,

Thank you for contributing this repo.

I have a question about the beta in NeRF-w. In NeRF-w paper, Eq. (12) shows the beta is calculated like 

```Python
# out[..., 8] is the beta output from MLPs
transient_betas = beta_min + torch.log(1 + torch.exp(out[..., 8]))
```

But I do not see there are similar lines in this code. 

And I have read the 'difference part with the original paper' part in the README.md. I can understand that the beta_min addition is operated after compositing. 

I just feel confused why you calculate beta in the way of this code.

Thanks.

**Comment by kwea123** [comment]
The `log(1+exp(...))` is just `softplus`, which I already have in the network activation:
https://github.com/kwea123/nerf_pl/blob/f121fc135dbc75d4edccedfb7d08b58a64fc8c88/models/nerf.py#L101
so my `out[..., 8]` already corresponds to his `log(1+e^beta_i(t))` in the equation.
