### ISSUE TITLE
Testing on an unscene Scene

### ISSUE THREAD

**Issue by Kartik-Teotia** [kwea123/nerf_pl#87]
Hi, I am looking into extending NeRF to generalize across different subjects in our camera setup. I am well aware that the original NeRF version cannot generalize to new scenes but I want to see how it looks. How do I test it on a scene with same camera poses but the centered object has changed, so its essentially a new scene? Running eval.py only queries xyz and direction, which makes sense but I want to know how do I test I test a network learned on one scene on a different scene?

Sorry if the question is too basic.

**Comment by kwea123** [comment]
>I am well aware that the original NeRF version cannot generalize to new scenes.
So there is no way you can check "how it looks" in a new scene. The network is learnt to represent the scene that it is trained on, so no way it can know what the new object looks like. There are many works that allow generalization now, I suggest that you check them, e.g. MVSNeRF or IBRNet.
