### ISSUE TITLE
Killed by linux

### ISSUE THREAD

**Issue by BoMingZhao** [kwea123/nerf_pl#88]
Hi, thanks for the great work!
And when I was training, I found that my GPU only used half of the memory. So I want to increase the chunk or batch size. But this caused the python running program to be killed by linux. Do you know any way to improve this?

**Comment by kwea123** [comment]
I don't know much about this issue, but it seems that it's because of insufficient RAM https://discuss.pytorch.org/t/code-stopping-with-text-killed/13827/3. How much RAM do you have? You can see by `free -mh`. And how much chunk/batch size did you use when the problem occurred?

**Comment by BoMingZhao** [comment]
> I don't know much about this issue, but it seems that it's because of insufficient RAM https://discuss.pytorch.org/t/code-stopping-with-text-killed/13827/3. How much RAM do you have? You can see by `free -mh`. And how much chunk/batch size did you use when the problem occurred?

thanks. As you said, it is indeed because of the ram problem
I use image-scale=2 batch-size = 1024 and chunk-size = 32*1024

**Comment by kwea123** [comment]
So did you solve this issue?

**Comment by BoMingZhao** [comment]
> So did you solve this issue?

yes，thank u
