### ISSUE TITLE
Bad texture after reconstructing colored mesh

### ISSUE THREAD

**Issue by Kasidit0052** [kwea123/nerf_pl#89]
Hello,

First, Thank you for creating this repository. Currently, I am trying to reconstruct colored mesh using your Colab. However, there are an unwanted artifacts on the output result. From the image below, figure coat are wrongly color when sigma=20. When reducing sigma, it is possible to improve the mesh. However, the output mesh is too noisy in this situation.

![result](https://user-images.githubusercontent.com/60087310/127426647-cf367eac-89f9-40a2-8a40-f866c6228f70.jpg)

This is the 3d reconstruction config:
```
occ_threshold = 0.2
xmin, xmax = -0.5, 0.5 
ymin, ymax = -0.5, 0.5 
zmin, zmax = -2.04, -0.64 
sigma_threshold = 5. &&  20.     
```

If possible, could you please elaborate the problem since modifying the occluded threshold doesn't help it either and nerf training result seem to be good also **(training_psnr = 28.8 and val_psnr = 28.0)**. I am happy to provide checkpoint and poses_bounds.py if needed.

Thank you!

**Comment by kwea123** [comment]
Hi, I think the mesh you get is probably the best we can get from this algorithm.
The bad texture problem is a known limitation, and we don't have solution currently. There are some works dealing with texture, and also mesh quality (by removing the dependency on sigma). I might try to implement some of these features in the future, but there is no plan currently.
