### ISSUE TITLE
torchsearchsorted  error

### ISSUE THREAD

**Issue by stone100010** [kwea123/nerf_pl#9]
File "/home/hsc/anaconda3/envs/nerfpl/lib/python3.6/site-packages/torchsearchsorted/searchsorted.py", line 41, in searchsorted
    raise Exception('torchsearchsorted on CUDA device is asked, but it seems '
Exception: torchsearchsorted on CUDA device is asked, but it seems that it is not available. Please install it

**Comment by kwea123** [comment]
again, installation problem, check your cuda first...
