### ISSUE TITLE
Dataloader for jpg images

### ISSUE THREAD

**Issue by darthgera123** [kwea123/nerf_pl#91]
**Describe the bug**
Is there a script to run with jpg images as described in the videos. Im trying to run nerfw and on my real world images but it needs tsv. The dataloader is not straightforward to edit so need help with that

**Which branch you use**
Only issues of the *dev* and *nerfw* branches will be considered currently!
nerfw

@kwea123 please help. BTw thanks for this very neat implementation and documentation. Helped a lot

**Comment by kwea123** [comment]
I suggest that you use `dev` branch because `nerfw` is only for showing nerf-w paper re-implementation results. In `dev` branch there shouldn't be issue using any image extension.
