### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by ariG23498** [kwea123/nerf_pl#97]
https://github.com/kwea123/nerf_pl/blob/2ca26add4f85218a97f6825e3eb0b9db19e7bab5/datasets/blender.py#L28-L31

In the code above we are doing the following
```
focal = 0.5 * 800 / tan(theta)
focal = focal * W / 800
```
which essentailly boils down to 
```
focal = 0.5 * W / tan(theta)
```

**Comment by kwea123** [comment]
This is not a bug, you are right too.
